### ISSUE TITLE
Align app_version struct member types to MCUBOOT image_version struct members 

### ISSUE THREAD

**Issue by tdbenson** [circuitdojo/zephyr-template#2]
Would it make sense to define the [app_version](https://github.com/circuitdojo/zephyr-template/blob/fc21ed5a4aaa109382892df0b24051b8290bdf1e/src/version/app_version.h#L18) struct to more closely align with the [ MCUBOOT image_version struct](https://github.com/mcu-tools/mcuboot/blob/2b822276cd6338d2a411ba46842017f66ca8c65d/boot/bootutil/include/bootutil/image.h#L111)?

Specifically the sizes of `patch` and `commit`. It seems like those could grow beyond the range of a byte (potentially), unless I'm misunderstanding the workflow for versioning. 

I don't think anything else should be changed, in fact its nice having the hash and build type information.

**Comment by jaredwolff** [comment]
Not a bad idea. I haven't had a chance to play with a more direct Mcuboot integration. Maybe soon though!

**Comment by tdbenson** [comment]
I mentioned this in a youtube comment, but I believe setting [CONFIG_MCUBOOT_EXTRA_IMGTOOL_ARGS](https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_MCUBOOT_EXTRA_IMGTOOL_ARGS.html)  to "--version x.y.z+c" is the only way at the moment. Maybe the cmake script can generate and place it at the end of version.conf, unless there's a better place.

**Comment by jaredwolff** [comment]
I had to add this line to my CMakeLists.txt.

```
file(APPEND conf/version.conf "CONFIG_MCUBOOT_IMAGE_VERSION=\"${version_major}.${version_minor}.${version_patch}+${version_commit}\"\n")
```

Give it a shot on your end and let me know how it goes @tdbenson

**Comment by tdbenson** [comment]
Thanks. That will work nicely. I'm surprised this option isn't defined in the official Zephyr repository.
