### ISSUE TITLE
Unsupported architecture for Zephyr Tools

### ISSUE THREAD

**Issue by nik012003** [circuitdojo/zephyr-template#4]
I get this error on my arm workstation
`Linux fedora 6.3.8-450.asahi.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Tue Jun 20 23:55:43 UTC 2023 aarch64 GNU/Linux`
How can I solve this? I can build zephyr just fine using the cli tools.

**Comment by jaredwolff** [comment]
The tools don't support aarch64 Linux (only aarch64 Mac at the moment).  This also isn't the correct repository. Feel free to open a ticket here: https://github.com/circuitdojo/zephyr-tools
